name: optimize_and_translate
description: A handy tool for optimization of arb files on flutter, applies transition
version: 0.0.1
homepage: https://github.com/ndasim/clear_unused_arb_keys

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  console_bars: 1.1.0
  translator: 0.1.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
